# -----------------------------------------------------------------
# Exchange family contract source
# -----------------------------------------------------------------
[ContractFamily.Identity]
policy_agent = { source = "${home}/contracts/identity/_identity_policy_agent.b64" }
signature_authority = { source = "${home}/contracts/identity/_identity_signature_authority.b64" }
wallet = { source = "${home}/contracts/identity/_identity_identity.b64" }
