#
# SPDX-License-Identifier: Apache-2.0
#

name: PDO CONTRACTS CI
on: [pull_request, push]
jobs:
    pdo_ci:
        if: "!contains(github.event.commits[0].message, '[skip ci]')"
        name: PDO CONTRACTS CI Job
        runs-on: ubuntu-22.04

        steps:
            - name: Check out repo
              uses: actions/checkout@v4
              with:
                  submodules: 'recursive'
                  fetch-tags: 'true'

            - name: Provide a name for the branch for use in building the images
              env:
                  PDO_INTERPRETER: wawaka
                  PDO_LOG_LEVEL: warning
              run: |
                  git describe --dirty
                  # git checkout -b ci-test-branch
                  # . private-data-objects/build/common-config.sh


            # - name: Build PDO images
            #   run: |
            #       make -C docker build_pdo_images

            # - name: Build and run tests for the full suite of contract families
            #   if: "!contains(github.event.commits[0].message, '[example]')"
            #   run: |
            #       # The creation of a dummy branch is necessary for the CI tests
            #       # to work on PRs. Based on empirical results, in the absence of
            #       # this command, CI tests work on the main branch and on local
            #       # branches. However, they fail as a PR is created.
            #       make -C docker test

            # - name: Build and run tests for the example contract family
            #   if: "contains(github.event.commits[0].message, '[example]')"
            #   run: |
            #       # The creation of a dummy branch is necessary for the CI tests
            #       # to work on PRs. Based on empirical results, in the absence of
            #       # this command, CI tests work on the main branch and on local
            #       # branches. However, they fail as a PR is created.
            #       make -C docker example
