#
# SPDX-License-Identifier: Apache-2.0
#

name: PDO CONTRACTS CI
on: [pull_request, push]
jobs:
    pdo_ci:
        if: "!contains(github.event.commits[0].message, '[skip ci]')"
        name: PDO CONTRACTS CI Job
        runs-on: ubuntu-22.04

        steps:
            - name: Check out repo
              uses: actions/checkout@v4
              with:
                  submodules: recursive
                  fetch-depth: 0

            - name: Fetch tags
              run: |
                git rev-parse --count v0.1.0

            # - name: Configure PDO and build the images
            #   env:
            #       PDO_INTERPRETER: wawaka
            #       PDO_LOG_LEVEL: warning
            #   run: |
            #       . private-data-objects/build/common-config.sh
            #       make -C docker build_pdo_images

            # - name: Build and run tests for the full suite of contract families
            #   if: "!contains(github.event.commits[0].message, '[example]')"
            #   run: |
            #       # The creation of a dummy branch is necessary for the CI tests
            #       # to work on PRs. Based on empirical results, in the absence of
            #       # this command, CI tests work on the main branch and on local
            #       # branches. However, they fail as a PR is created.
            #       make -C docker test

            # - name: Build and run tests for the example contract family
            #   if: "contains(github.event.commits[0].message, '[example]')"
            #   run: |
            #       # The creation of a dummy branch is necessary for the CI tests
            #       # to work on PRs. Based on empirical results, in the absence of
            #       # this command, CI tests work on the main branch and on local
            #       # branches. However, they fail as a PR is created.
            #       make -C docker example
