#
# SPDX-License-Identifier: Apache-2.0
#

name: PDO Contracts Full Test
on:
  push:
    branches-ignore:
      - test.*

jobs:
    pdo_ci:
        if: "!contains(github.event.commits[0].message, '[skip ci]')"
        name: PDO Contracts Full Test
        runs-on: ubuntu-22.04

        steps:
            - name: Check out repo
              uses: actions/checkout@v4
              with:
                  submodules: recursive
                  fetch-depth: 0
                  fetch-tags: true

            - name: Set the version
              run: |
                echo "CONTRACTS_VERSION=$(git rev-list cfd6...$GITHUB_SHA)" >> $GITHUB_ENV
                echo "PDO_VERSION=$(cd private-data-objects; git rev-list 5fa3...HEAD --count)" >> $GITHUB_ENV

            - name: Show the version
              run: |
                echo CONTRACTS_VERSION is $CONTRACTS_VERSION
                echo PDO_VERSION is $PDO_VERSION


            # - name: Configure PDO and build the base images
            #   env:
            #       PDO_INTERPRETER: wawaka
            #       PDO_LOG_LEVEL: warning
            #   run: |
            #       . private-data-objects/build/common-config.sh
            #       make -C docker build_pdo_images

            # - name: Build and run tests for the full suite of contract families
            #   if: "!contains(github.event.commits[0].message, '[example]')"
            #   run: |
            #       make -C docker test

            # - name: Build and run tests for the example contract family
            #   if: "contains(github.event.commits[0].message, '[example]')"
            #   run: |
            #       make -C docker example
